on:
  pull_request:
    types: [closed]

name: shinyapps-teardown

jobs:
  shinyapps-terminate:
    runs-on: ubuntu-20.04

    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      APP_BASENAME: "my-app"
      APP_INCLUDE_BRANCH_SUFFIX: "TRUE"
      SHINYAPPS_IO_TOKEN: ${{ secrets.SHINYAPPS_IO_TOKEN }}
      SHINYAPPS_IO_SECRET: ${{ secrets.SHINYAPPS_IO_SECRET }}
      SHINYAPPS_IO_ACCOUNT: ${{ secrets.SHINYAPPS_IO_ACCOUNT }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      SCRIPT: ".github/scripts/deploy-shinyapps-io.R"

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install app-termination R dependencies
        run: |
          options(warn = 2)
          source("${{ env.SCRIPT }}")
          install_script_deps()
        shell: Rscript {0}

      - name: Teardown the app for this closed branch
        run: |
          options(warn = 2)
          source("${{ env.SCRIPT }}")
          terminate(
            account = "${{ env.SHINYAPPS_IO_ACCOUNT }}",
            include_branch = ${{ env.APP_INCLUDE_BRANCH_SUFFIX }}
          )
        shell: Rscript {0}
